package com.ecommerce.dao;
import com.ecommerce.model.*; import com.ecommerce.util.DBUtil; import java.sql.*; import java.util.*; import java.math.BigDecimal;
public class OrderDAO {
 private Order map(ResultSet rs)throws SQLException{Order o=new Order();o.setId(rs.getInt("id"));o.setUserId(rs.getInt("user_id"));o.setOrderDate(rs.getTimestamp("order_date"));o.setTotalAmount(rs.getBigDecimal("total_amount"));o.setStatus(rs.getString("status"));try{o.setCustomerName(rs.getString("customer_name"));}catch(Exception ignored){}return o;}
 public int createOrder(User user, List<CartItem> cart)throws Exception{Connection c=DBUtil.getConnection();try{c.setAutoCommit(false);BigDecimal total=BigDecimal.ZERO;for(CartItem item:cart) total=total.add(item.getSubtotal());PreparedStatement ps=c.prepareStatement("insert into orders(user_id,total_amount,status) values(?,?,?)",Statement.RETURN_GENERATED_KEYS);ps.setInt(1,user.getId());ps.setBigDecimal(2,total);ps.setString(3,"Beklemede");ps.executeUpdate();ResultSet keys=ps.getGeneratedKeys();keys.next();int orderId=keys.getInt(1);ProductDAO pdao=new ProductDAO();PreparedStatement itemPs=c.prepareStatement("insert into order_items(order_id,product_id,quantity,unit_price,subtotal) values(?,?,?,?,?)");for(CartItem item:cart){pdao.decreaseStock(c,item.getProduct().getId(),item.getQuantity());itemPs.setInt(1,orderId);itemPs.setInt(2,item.getProduct().getId());itemPs.setInt(3,item.getQuantity());itemPs.setBigDecimal(4,item.getProduct().getPrice());itemPs.setBigDecimal(5,item.getSubtotal());itemPs.addBatch();}itemPs.executeBatch();c.commit();return orderId;}catch(Exception e){c.rollback();throw e;}finally{c.close();}}
 public List<Order> findByUser(int userId)throws Exception{return query("select o.*,u.full_name customer_name from orders o join users u on o.user_id=u.id where o.user_id="+userId+" order by o.id desc");}
 public List<Order> findAll()throws Exception{return query("select o.*,u.full_name customer_name from orders o join users u on o.user_id=u.id order by o.id desc");}
 private List<Order> query(String sql)throws Exception{List<Order> l=new ArrayList<>();try(Connection c=DBUtil.getConnection();Statement st=c.createStatement();ResultSet rs=st.executeQuery(sql)){while(rs.next())l.add(map(rs));}return l;}
 public Order findById(int id)throws Exception{try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("select o.*,u.full_name customer_name from orders o join users u on o.user_id=u.id where o.id=?")){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){if(!rs.next())return null;Order o=map(rs);o.setItems(findItems(id));return o;}}}
 public List<OrderItem> findItems(int orderId)throws Exception{List<OrderItem> l=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("select oi.*,p.name product_name from order_items oi join products p on oi.product_id=p.id where order_id=?")){ps.setInt(1,orderId);try(ResultSet rs=ps.executeQuery()){while(rs.next()){OrderItem i=new OrderItem();i.setId(rs.getInt("id"));i.setOrderId(rs.getInt("order_id"));i.setProductId(rs.getInt("product_id"));i.setQuantity(rs.getInt("quantity"));i.setUnitPrice(rs.getBigDecimal("unit_price"));i.setSubtotal(rs.getBigDecimal("subtotal"));i.setProductName(rs.getString("product_name"));l.add(i);}}}return l;}
 public void updateStatus(int id,String status)throws Exception{try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("update orders set status=? where id=?")){ps.setString(1,status);ps.setInt(2,id);ps.executeUpdate();}}
 public int count()throws Exception{try(Connection c=DBUtil.getConnection();Statement st=c.createStatement();ResultSet rs=st.executeQuery("select count(*) from orders")){rs.next();return rs.getInt(1);}}
 public int pendingCount()throws Exception{try(Connection c=DBUtil.getConnection();Statement st=c.createStatement();ResultSet rs=st.executeQuery("select count(*) from orders where status='Beklemede'")){rs.next();return rs.getInt(1);}}
}
