package com.ecommerce.dao;
import com.ecommerce.model.Product; import com.ecommerce.util.DBUtil; import java.sql.*; import java.util.*; import java.math.BigDecimal;
public class ProductDAO {
 private Product map(ResultSet rs)throws SQLException{Product p=new Product();p.setId(rs.getInt("id"));p.setCategoryId(rs.getInt("category_id"));p.setName(rs.getString("name"));p.setDescription(rs.getString("description"));p.setPrice(rs.getBigDecimal("price"));p.setStock(rs.getInt("stock"));p.setImageUrl(rs.getString("image_url"));p.setActive(rs.getBoolean("is_active"));p.setCreatedAt(rs.getTimestamp("created_at"));try{p.setCategoryName(rs.getString("category_name"));}catch(Exception ignored){} return p;}
 private String base="select p.*,c.name category_name from products p join categories c on p.category_id=c.id";
 public List<Product> findActive(Integer categoryId,String q)throws Exception{String sql=base+" where p.is_active=1 and c.is_active=1"; if(categoryId!=null)sql+=" and p.category_id=?"; if(q!=null&&!q.trim().isEmpty())sql+=" and (p.name like ? or p.description like ?)"; sql+=" order by p.id desc"; List<Product> l=new ArrayList<>(); try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement(sql)){int i=1;if(categoryId!=null)ps.setInt(i++,categoryId);if(q!=null&&!q.trim().isEmpty()){ps.setString(i++,"%"+q+"%");ps.setString(i++,"%"+q+"%");}try(ResultSet rs=ps.executeQuery()){while(rs.next())l.add(map(rs));}}return l;}
 public List<Product> findAll()throws Exception{List<Product> l=new ArrayList<>();try(Connection c=DBUtil.getConnection();Statement st=c.createStatement();ResultSet rs=st.executeQuery(base+" order by p.id desc")){while(rs.next())l.add(map(rs));}return l;}
 public Product findById(int id)throws Exception{try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement(base+" where p.id=?")){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){return rs.next()?map(rs):null;}}}
 public void save(Product p)throws Exception{try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("insert into products(category_id,name,description,price,stock,image_url,is_active) values(?,?,?,?,?,?,?)")){fill(ps,p);ps.executeUpdate();}}
 public void update(Product p)throws Exception{try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("update products set category_id=?,name=?,description=?,price=?,stock=?,image_url=?,is_active=? where id=?")){fill(ps,p);ps.setInt(8,p.getId());ps.executeUpdate();}}
 private void fill(PreparedStatement ps,Product p)throws SQLException{ps.setInt(1,p.getCategoryId());ps.setString(2,p.getName());ps.setString(3,p.getDescription());ps.setBigDecimal(4,p.getPrice());ps.setInt(5,p.getStock());ps.setString(6,p.getImageUrl());ps.setBoolean(7,p.isActive());}
 public void softDelete(int id)throws Exception{try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("update products set is_active=0 where id=?")){ps.setInt(1,id);ps.executeUpdate();}}
 public void decreaseStock(Connection c,int id,int qty)throws Exception{try(PreparedStatement ps=c.prepareStatement("update products set stock=stock-? where id=? and stock>=?")){ps.setInt(1,qty);ps.setInt(2,id);ps.setInt(3,qty); if(ps.executeUpdate()==0)throw new SQLException("Stok yetersiz: ürün "+id);}}
 public int count()throws Exception{try(Connection c=DBUtil.getConnection();Statement st=c.createStatement();ResultSet rs=st.executeQuery("select count(*) from products")){rs.next();return rs.getInt(1);}}
}
