package com.ecommerce.controller;
import com.ecommerce.dao.*; import com.ecommerce.model.*; import com.ecommerce.util.View; import javax.servlet.*; import javax.servlet.annotation.WebServlet; import javax.servlet.http.*; import java.io.IOException; import java.math.BigDecimal;
@WebServlet({"/admin/login","/admin/logout","/admin/dashboard","/admin/categories","/admin/category-form","/admin/products","/admin/product-form","/admin/orders","/admin/order-detail","/admin/users"})
public class AdminServlet extends HttpServlet{
 protected void doGet(HttpServletRequest req,HttpServletResponse resp)throws ServletException,IOException{try{String p=req.getServletPath(); if(p.endsWith("/logout")){req.getSession().invalidate();resp.sendRedirect(req.getContextPath()+"/admin/login");return;} if(p.endsWith("/login")){View.forward(req,resp,"admin/login.jsp");return;} if(p.endsWith("/dashboard")){req.setAttribute("productCount",new ProductDAO().count());req.setAttribute("categoryCount",new CategoryDAO().count());req.setAttribute("userCount",new UserDAO().count());req.setAttribute("orderCount",new OrderDAO().count());req.setAttribute("pendingCount",new OrderDAO().pendingCount());View.forward(req,resp,"admin/dashboard.jsp");}
 else if(p.endsWith("/categories")){req.setAttribute("categories",new CategoryDAO().findAll());View.forward(req,resp,"admin/categories.jsp");}
 else if(p.endsWith("/category-form")){String id=req.getParameter("id"); if(id!=null)req.setAttribute("category",new CategoryDAO().findById(Integer.parseInt(id)));View.forward(req,resp,"admin/category-form.jsp");}
 else if(p.endsWith("/products")){req.setAttribute("products",new ProductDAO().findAll());View.forward(req,resp,"admin/products.jsp");}
 else if(p.endsWith("/product-form")){String id=req.getParameter("id"); if(id!=null)req.setAttribute("product",new ProductDAO().findById(Integer.parseInt(id)));req.setAttribute("categories",new CategoryDAO().findAll());View.forward(req,resp,"admin/product-form.jsp");}
 else if(p.endsWith("/orders")){req.setAttribute("orders",new OrderDAO().findAll());View.forward(req,resp,"admin/orders.jsp");}
 else if(p.endsWith("/order-detail")){req.setAttribute("order",new OrderDAO().findById(Integer.parseInt(req.getParameter("id"))));View.forward(req,resp,"admin/order-detail.jsp");}
 else if(p.endsWith("/users")){req.setAttribute("users",new UserDAO().findAll());View.forward(req,resp,"admin/users.jsp");}
 }catch(Exception e){throw new ServletException(e);}}
 protected void doPost(HttpServletRequest req,HttpServletResponse resp)throws ServletException,IOException{try{req.setCharacterEncoding("UTF-8");String p=req.getServletPath(); if(p.endsWith("/login")){User u=new UserDAO().login(req.getParameter("email"),req.getParameter("password")); if(u==null||!"ADMIN".equals(u.getRole())){req.setAttribute("error","Admin bilgileri hatalı");View.forward(req,resp,"admin/login.jsp");return;}req.getSession().setAttribute("user",u);resp.sendRedirect(req.getContextPath()+"/admin/dashboard");}
 else if(p.endsWith("/categories")){String action=req.getParameter("action");CategoryDAO dao=new CategoryDAO(); if("delete".equals(action)){dao.softDelete(Integer.parseInt(req.getParameter("id")));}else{Category c=new Category();String id=req.getParameter("id");if(id!=null&&!id.isEmpty())c.setId(Integer.parseInt(id));c.setName(req.getParameter("name"));c.setDescription(req.getParameter("description"));c.setActive("on".equals(req.getParameter("active"))); if(c.getName()==null||c.getName().trim().isEmpty()){req.setAttribute("error","Kategori adı boş olamaz");req.setAttribute("category",c);View.forward(req,resp,"admin/category-form.jsp");return;} if(c.getId()>0)dao.update(c);else dao.save(c);}resp.sendRedirect(req.getContextPath()+"/admin/categories");}
 else if(p.endsWith("/products")){String action=req.getParameter("action");ProductDAO dao=new ProductDAO(); if("delete".equals(action)){dao.softDelete(Integer.parseInt(req.getParameter("id")));}else{Product pr=new Product();String id=req.getParameter("id");if(id!=null&&!id.isEmpty())pr.setId(Integer.parseInt(id));pr.setCategoryId(Integer.parseInt(req.getParameter("categoryId")));pr.setName(req.getParameter("name"));pr.setDescription(req.getParameter("description"));pr.setPrice(new BigDecimal(req.getParameter("price")));pr.setStock(Integer.parseInt(req.getParameter("stock")));pr.setImageUrl(req.getParameter("imageUrl"));pr.setActive("on".equals(req.getParameter("active"))); if(pr.getName().trim().isEmpty()||pr.getPrice().compareTo(BigDecimal.ZERO)<=0||pr.getStock()<0){req.setAttribute("error","Ürün adı, fiyat ve stok değerlerini kontrol edin");req.setAttribute("categories",new CategoryDAO().findAll());req.setAttribute("product",pr);View.forward(req,resp,"admin/product-form.jsp");return;} if(pr.getId()>0)dao.update(pr);else dao.save(pr);}resp.sendRedirect(req.getContextPath()+"/admin/products");}
 else if(p.endsWith("/orders")){new OrderDAO().updateStatus(Integer.parseInt(req.getParameter("id")),req.getParameter("status"));resp.sendRedirect(req.getContextPath()+"/admin/orders");}}
 catch(Exception e){throw new ServletException(e);}}
}
